version: '3'

services:
  redis:
    image: redis
    command: redis-server 
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2022!"
    ports:
      - "5432:5432"