spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    virtual-host: ${RABBITMQ_VHOST:teste_performance}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:rabbit}
    password: ${RABBITMQ_PASSWORD:123456}
    listener:
      simple:
        concurrency: ${RABBITMQ_MIN_CONCURRENCY:1}
        max-concurrency: ${RABBITMQ_MAX_CONCURRENCY:5}
        prefetch: ${RABBITMQ_PREFETCH:250}
  datasource:
     url: ${JDBC_URL:jdbc:mysql://localhost:3306/rabbit?allowPublicKeyRetrieval=true&useSSL=false}
     username: '${DATABASE_USER:root}'
     password: ${DATABASE_PASS:123456}
     hikari:
      maximumPoolSize: 10
      minimumIdle: 1
      keepaliveTime: 30000
      max-lifetime: 45000
  jpa:
     show-sql: ${SHOW_SQL:true}
     hibernate:
        ddl-auto: update
        enable_lazy_load_no_trans: true
     properties:
        hibernate:
           dialect: org.hibernate.dialect.MySQLDialect
        

server:
  port : ${PORT:8080}
  
jwt:
  secret: ${JWT_SECRET:teste}
  
redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
  
rabbit:
  exchange: ${RABBITMQ_EXCHANGE:teste}
  routing-key: ${RABBITMQ_KEY:teste_key}
  queue: ${RABBITMQ_QUEUE:teste_performance_queue}

   
logging:
    level:
      root: ${LOGGING_LEVEL:INFO}  
      org:
       hibernate:
        SQL: ${LOGGING_LEVEL_HIBERNATE:INFO}   
      